-- AlterTable
ALTER TABLE "ProdutoImagem" ADD COLUMN     "offsetX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "offsetY" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
